### PR TITLE
Added query support

### PR DESCRIPTION
**Pull request by williamcoates**
You can now query using indexes like:

```javascript
dynamo
  .table(‘foo’)
  .query(
     indexName: ‘global-secondary-index’
     keyConditions: [
       {column: ‘hash_key’, value: ’foo’}
       {column: ‘range_key’, value: ‘bar’}
     ]
      filters: [
         {column: ‘other’, value: ‘foo’}
      ]
   )
```

### CODE REVIEW

**Comment by victorquinn** [comment]
Love this enhancement too, thanks again @williamcoates !

**Comment by camjackson** [comment]
Is this documented anywhere? I can't see it on dynastyjs.com.

**Comment by camjackson** [comment]
Oh, it's not release yet. Any chance this will be released soon?

**Comment by daryl** [comment]
Why's this not on npm?

**Comment by victorquinn** [comment]
@daryl it is on npm and has been for a few months now...

The documentation hasn't been updated yet so perhaps that's the source of confusion.

**Pull request merged**
