### PR TITLE
Added ability to specify exclusive start key on scan

### PR DESCRIPTION
**Pull request by timhuff**
This is a minor change that enables users to perform the actions the documentation says they should be able to. Users should be given the ability to iterate across a given table.

### CODE REVIEW

**Comment by malexdev** [comment]
So, this patch is pretty much a must have, and resolves the issue perfectly. It's been over a year. Is this project dead, or are we going to be able to merge this in? :)

**Comment by timhuff** [comment]
@victorquinn Is there some reason this was never merged? We should either merge it or close it this request.

@malexdev: I stopped using this library (and DynamoDB, for that matter) ages ago but I believe what your wanting to do can be achieved with `.processAllPages`. I don't have an environment to easily test this anymore but you might be able to do something like this:

```coffee
awsTrans = require 'dynasty/aws-translators.coffee'
getAllItems = (dynamoTable)->
    dynamoTable.key.then ->
        deferred = Q.defer()
        awsTrans.processAllPages(deferred, dynamoTable.parent.dynamo, 'scan', TableName: dynamoTAble.name)
        deferred.promise

getAllItems(someDynamoTable).progress (pageOfItems)->
    console.log "#{pageOfItems.length} items scanned"
```

Not exactly the most elegant solution but it might do the trick

**Comment by victorquinn** [comment]
Apologies, I could have sworn I had commented on this ages ago and was awaiting changes. Apparently I never did so that's 100% my fault.

But in brief this is because Dynasty is intended to be a cleaner abstraction from Dynamo, and as a result intentionally tries to not expose some of what are, in my opinion anyway, Dynamo's messy internals. 

This is why Dynasty has methods like `find` and `insert` which (I think) are cleaner and more intuitive than Dynamo's `GetItem` and `PutItem`. 

So, while this change is super important, I just didn't like exposing the messy internals of Dynamo by having the Dynasty API get provided a `ExclusiveStartKey` where it should be something cleaner like `offset`. 

However, this also entails not only adding it here but also translating the response we get from Dynamo before it gets to the end user.

Anyway, my sincerest apologies this languished for so long, I will resolve this shortly (within the next day or so).

**Comment by timhuff** [comment]
I understand your objection in that regard (I remember that, when I implemented it, I basically had the thought of "well... I guess the user will need to provide the start key..."). A use case to consider: back when I was using dynamo, I actually relied exclusively on my fork largely because I needed this functionality - I had a table set up with a primary key being "user id" and there were events (sometimes several pages of them) with a timestamp range key stored in the table that needed to be returned to the user. So I needed to scan the table for a give user id and return all events for that user (or at least several pages of them).

**Comment by malexdev** [comment]
@victorquinn I'm definitely on board with hiding messy internals. 

If you'd like (especially since I was the one that brought this up again) I can make a patch that makes `scan` function as you outlined. I definitely don't want to be one of those people that comes in to the issues and complains but isn't willing to help fix it :) just let me know.

**Comment by victorquinn** [comment]
@timhuff gotcha, again apologies this got lost for so long. 

To make sure people can make progress, I'm going to accept this, cut 0.2.7 release immediately, and start work on a 1.0 release that will seek to clean up the API across the board. 

This will possibly introduce some breaking changes to make it clean, but the major version bump should help isolate the issues and ensure that future users have the nice clean API we were striving for when this project was initially created (almost 3.5 years ago now!).

**Comment by victorquinn** [comment]
Ok, this is live on npm as 0.2.7!

**Comment by victorquinn** [comment]
@malexdev would certainly love the help if you want to give it! 

I'm actively working on the cleanup now on a 1.0 branch which I just pushed -- you should be able to make any PRs to that branch.

**Comment by timhuff** [comment]
@victorquinn No worries. I appreciated the work you had put into it thus far and it required only minor modifications to make useful for my use cases. While you work on structuring the API, I'd like to recommend an API that worked rather well for me. It's a chainable promise-based API that worked like this: 

`DB.entries.find().hash(userId)` would provide (via `.then`) all entries that had the given hash key. `DB.entries.find()` would provide the entire table. I can't quite remember but I think I also had it so that `DB.entries.find().hash(userId).range(timestamp)` would provide a specific entry. Just a thought.

**Pull request merged**
