### PR TITLE
fixes #104

### LINKED ISSUE #104: dynasty breaks with latest aws-sdk
Hi there,  I was trying to use dynasty with  "aws-sdk": "^2.307.0", we got it working with  "aws-sdk": "2.255.1"  on older code but it breaks big time. 

Pasting here the error: 

```
{
    "errorMessage": "Cannot promisify an API that has normal methods with 'Async'-suffix\n\n    See http://goo.gl/iWrZbw\n",
    "errorType": "TypeError",
    "stackTrace": [
        "",
        "    See http://goo.gl/iWrZbw",
        "",
        "checkValid (/var/task/node_modules/dynasty/node_modules/bluebird/js/main/promisify.js:55:27)",
        "promisifiableMethods (/var/task/node_modules/dynasty/node_modules/bluebird/js/main/promisify.js:78:5)",
        "promisifyAll (/var/task/node_modules/dynasty/node_modules/bluebird/js/main/promisify.js:241:9)",
        "Function.Promise.promisifyAll (/var/task/node_modules/dynasty/node_modules/bluebird/js/main/promisify.js:304:12)",
        "new Dynasty (/var/task/node_modules/dynasty/lib/dynasty.js:39:15)",
        "module.exports (/var/task/node_modules/dynasty/lib/dynasty.js:224:12)",
        "Object.<anonymous> (/var/task/src/utils.js:1:97)",
        "Module._compile (module.js:652:30)",
        "Object.Module._extensions..js (module.js:663:10)",
        "Module.load (module.js:565:32)",
        "tryModuleLoad (module.js:505:12)",
        "Function.Module._load (module.js:497:3)",
        "Module.require (module.js:596:17)",
        "require (internal/module.js:11:18)",
        "Object.<anonymous> (/var/task/src/automaticSwitch.js:10:56)",
        "Module._compile (module.js:652:30)",
        "Object.Module._extensions..js (module.js:663:10)",
        "Module.load (module.js:565:32)",
        "tryModuleLoad (module.js:505:12)",
        "Function.Module._load (module.js:497:3)",
        "Module.require (module.js:596:17)",
        "require (internal/module.js:11:18)",
        "Object.<anonymous> (/var/task/iopipe_handlers/automaticSwitch-iopipe.js:8:13)",
        "Module._compile (module.js:652:30)",
        "Object.Module._extensions..js (module.js:663:10)",
        "Module.load (module.js:565:32)",
        "tryModuleLoad (module.js:505:12)",
        "Function.Module._load (module.js:497:3)"
    ]
}
```
It seems like they added/changed some functions in the DynamoDB library, calling them with the async prefix, so bluebird goes nuts. 

https://github.com/petkaantonov/bluebird/wiki/Error:-Cannot-promisify-an-API-that-has-normal-methods

### PR DESCRIPTION
**Pull request by aterreno**
By changing the default promisify.all adding the optional suffix param, using Promise, so all the calls to the parent dynamo have been changed to reflect the change.

### CODE REVIEW

**Comment by victorquinn** [comment]
Thanks for the addition @aterreno looks great!

**Comment by aterreno** [comment]
👍

**Comment by aterreno** [comment]
@victorquinn any chance you might release a new version after this? our lambdas are starting to break up in prod while getting updated with the new version of aws sdk

**Comment by victorquinn** [comment]
Shit yes sorry, forgot to do that! Give me a few mins and I'll update when it's live on npm for you.

**Comment by victorquinn** [comment]
Published on npm as 0.3.10, sorry for the delay!

**Comment by aterreno** [comment]
Thanks man, much appreciated

**Pull request merged**
